import type { Service } from "@/sanity/lib/types";

export const growthServiceFallbacks: Service[] = [
  {
    _id: "fallback-meta-ads",
    title: "Meta Ads",
    slug: { current: "meta-ads" },
    shortDescription: "Facebook and Instagram ad strategy for businesses that need qualified enquiries, not random traffic.",
    serviceCategory: "Acquire",
    featured: true,
    displayOrder: 1,
    features: ["Campaign strategy", "Audience planning", "Creative direction", "Lead-focused tracking"],
    benefits: ["Reach active local and regional buyers", "Test offers quickly", "Improve lead quality with better follow-up"],
    process: [
      { title: "Audit", description: "Review offer, audience, page and current ad readiness." },
      { title: "Setup", description: "Prepare campaign structure, creatives and lead path." },
      { title: "Optimize", description: "Improve using lead quality, cost signals and business feedback." },
    ],
    ctaLabel: "Get Free Growth Audit",
    ctaHref: "/#audit",
    seoTitle: "Meta Ads Agency in Sikar and Jaipur",
    seoDescription: "Meta Ads planning and management for businesses in Sikar, Jaipur, Rajasthan and across India.",
  },
  {
    _id: "fallback-google-ads",
    title: "Google Ads",
    slug: { current: "google-ads" },
    shortDescription: "Search-led Google Ads for businesses that want to appear when customers are already looking.",
    serviceCategory: "Acquire",
    displayOrder: 2,
    features: ["Search intent planning", "Keyword structure", "Landing page alignment", "Conversion tracking guidance"],
    benefits: ["Capture high-intent demand", "Reduce wasted clicks", "Connect ads to real enquiry paths"],
    ctaLabel: "Get Free Growth Audit",
    ctaHref: "/#audit",
    seoTitle: "Google Ads Agency in Rajasthan",
    seoDescription: "Google Ads strategy for local and service businesses in Sikar, Jaipur, Rajasthan and India.",
  },
  {
    _id: "fallback-social-media-management",
    title: "Social Media Management",
    slug: { current: "social-media-management" },
    shortDescription: "Consistent social presence that builds trust, explains offers and supports lead generation.",
    serviceCategory: "Build Trust",
    displayOrder: 3,
    features: ["Content calendar", "Post planning", "Brand voice", "Offer-focused messaging"],
    benefits: ["Look active and credible", "Educate customers", "Support ads with stronger trust"],
    ctaLabel: "Get Free Growth Audit",
    ctaHref: "/#audit",
  },
  {
    _id: "fallback-content-strategy",
    title: "Content Strategy & Creation",
    slug: { current: "content-strategy" },
    shortDescription: "Content direction for reels, posts, offers and educational pieces that support business growth.",
    serviceCategory: "Build Trust",
    displayOrder: 4,
    features: ["Content pillars", "Offer messaging", "Creative briefs", "Posting direction"],
    benefits: ["Stop random posting", "Make the offer clearer", "Build long-term trust"],
    ctaLabel: "Get Free Growth Audit",
    ctaHref: "/#audit",
  },
  {
    _id: "fallback-seo",
    title: "SEO",
    slug: { current: "seo" },
    shortDescription: "Search visibility improvements for businesses that want more organic discovery and trust.",
    serviceCategory: "Build Trust",
    displayOrder: 5,
    features: ["Keyword direction", "On-page SEO", "Technical SEO checks", "Content opportunities"],
    benefits: ["Improve long-term visibility", "Build trust before enquiries", "Support paid and organic growth together"],
    ctaLabel: "Get Free Growth Audit",
    ctaHref: "/#audit",
  },
  {
    _id: "fallback-google-business-profile-management",
    title: "Google Business Profile Management",
    slug: { current: "google-business-profile-management" },
    shortDescription: "Google Maps and local profile improvements for businesses that rely on nearby customers.",
    serviceCategory: "Build Trust",
    displayOrder: 6,
    features: ["Profile cleanup", "Category and service review", "Post planning", "Local trust signals"],
    benefits: ["Improve local discovery", "Help customers trust the business faster", "Support Sikar, Jaipur and Rajasthan visibility"],
    ctaLabel: "Get Free Growth Audit",
    ctaHref: "/#audit",
  },
  {
    _id: "fallback-websites",
    title: "Websites",
    slug: { current: "websites" },
    shortDescription: "Premium business websites built to explain trust, services and enquiry paths clearly.",
    serviceCategory: "Convert",
    displayOrder: 7,
    features: ["Positioning-led pages", "Mobile-first layout", "Lead forms", "WhatsApp and call CTAs"],
    benefits: ["Make the first impression stronger", "Turn visitors into enquiries", "Support ads, SEO and social traffic"],
    ctaLabel: "Get Free Growth Audit",
    ctaHref: "/#audit",
  },
  {
    _id: "fallback-landing-pages",
    title: "Landing Pages",
    slug: { current: "landing-pages" },
    shortDescription: "Focused landing pages for campaigns, offers, lead magnets and local service enquiries.",
    serviceCategory: "Convert",
    displayOrder: 8,
    features: ["Offer structure", "Conversion copy", "Lead capture", "Fast mobile experience"],
    benefits: ["Improve ad conversion", "Reduce visitor confusion", "Create a focused enquiry path"],
    ctaLabel: "Get Free Growth Audit",
    ctaHref: "/#audit",
  },
  {
    _id: "fallback-lead-generation-systems",
    title: "Lead Generation Systems",
    slug: { current: "lead-generation-systems" },
    shortDescription: "Connected campaigns, pages, forms and WhatsApp flows designed to capture qualified enquiries.",
    serviceCategory: "Acquire",
    featured: true,
    displayOrder: 9,
    features: ["Lead path planning", "Form and WhatsApp flow", "Offer clarity", "Source tracking guidance"],
    benefits: ["Capture enquiries cleanly", "Understand where leads come from", "Improve response speed"],
    ctaLabel: "Get Free Growth Audit",
    ctaHref: "/#audit",
  },
  {
    _id: "fallback-automation-follow-up-systems",
    title: "Automation & Follow-up Systems",
    slug: { current: "automation-follow-up-systems" },
    shortDescription: "Simple follow-up systems that help businesses respond faster and avoid losing warm leads.",
    serviceCategory: "Scale",
    displayOrder: 10,
    features: ["Lead routing", "WhatsApp follow-up planning", "Response templates", "Basic automation mapping"],
    benefits: ["Reduce missed leads", "Keep communication consistent", "Support sales conversations"],
    ctaLabel: "Get Free Growth Audit",
    ctaHref: "/#audit",
  },
  {
    _id: "fallback-business-growth-consultation",
    title: "Business Growth Consultation",
    slug: { current: "business-growth-consultation" },
    shortDescription: "Focused consultation for business owners who need clarity before investing in marketing.",
    serviceCategory: "Scale",
    displayOrder: 11,
    features: ["Growth gap review", "Channel prioritization", "Offer discussion", "Practical action plan"],
    benefits: ["Avoid random spending", "Choose the right first step", "Get clear direction"],
    ctaLabel: "Get Free Growth Audit",
    ctaHref: "/#audit",
  },
];

const legacyServiceFallbacks: Service[] = [
  {
    _id: "legacy-web-apps",
    title: "Web Apps for Growth Operations",
    slug: { current: "web-apps" },
    shortDescription: "A secondary capability for browser-based lead capture, follow-up and internal growth workflows.",
    serviceCategory: "Secondary Capability",
    features: ["Lead capture workflows", "Internal follow-up screens", "Simple reporting interfaces", "Operational forms"],
    benefits: ["Support growth campaigns after the lead is captured", "Reduce missed enquiries", "Keep team workflows clearer"],
    ctaLabel: "Get Free Growth Audit",
    ctaHref: "/#audit",
    seoTitle: "Web Apps for Lead Capture and Growth Operations",
    seoDescription: "Secondary web app capability for lead capture, follow-up and business growth workflows by TrustFirst Solutions.",
  },
  {
    _id: "legacy-custom-software",
    title: "Custom Growth Systems",
    slug: { current: "custom-software" },
    shortDescription: "A secondary capability for custom workflows that support lead management, follow-up and business operations.",
    serviceCategory: "Secondary Capability",
    features: ["Custom enquiry workflows", "Follow-up process mapping", "Business operation forms", "Dashboard-style reporting needs"],
    benefits: ["Connect marketing activity with operations", "Make follow-up more consistent", "Clarify what should be automated first"],
    ctaLabel: "Get Free Growth Audit",
    ctaHref: "/#audit",
    seoTitle: "Custom Growth Systems for Business Operations",
    seoDescription: "Secondary custom systems capability for lead management, follow-up and business operations by TrustFirst Solutions.",
  },
];

export function getGrowthServiceFallback(slug: string) {
  return [...growthServiceFallbacks, ...legacyServiceFallbacks].find((service) => service.slug?.current === slug);
}
